"""
Swept‑volume analysis for dual‑arm strawberry‑picking robot.

Functionality
=============
1. Forward Kinematics (FK): given an IK joint solution ``q`` and the arm base
   transform, compute the vehicle‑frame positions of **every link origin** along
   the kinematic chain (base_link → link1 → … → link7 → ee_link).
2. Swept‑volume construction: for every reachable target in the ROI table, use
   the *best* IK solution to compute all link positions, then collect them by
   arm and by target region.
3. Safety‑boundary search: find the x‑boundary inside the interference zones
   (B2 / B5) such that, when the *left* end‑effector works only in the
   left‑only zone and the *right* end‑effector works only within the sub‑region
   of B2/B5 beyond that boundary, their link swept volumes are guaranteed
   disjoint — and vice versa.
4. Visualization: multi‑panel plot showing
   (a) per‑arm link swept volumes,
   (b) combined dual‑arm swept volumes with overlap highlighted,
   (c) safety‑boundary overlay.

Usage
-----
    cd roi
    python swept_volume_analysis.py

The script loads the pre‑built ``roi_table.pkl`` (generated by
``build_roi_table.py``) and the URDF, then produces the analysis images
in ``roi/results/``.
"""

import os
import pickle
import xml.etree.ElementTree as ET

import numpy as np
import matplotlib.pyplot as plt
import matplotlib.patches as patches
from scipy.spatial import ConvexHull, Delaunay

from build_roi_table import (
    CONFIG,
    classify_entry,
    load_base_transforms_from_urdf,
    rpy_to_rot,
    xyzrpy_to_T,
)

# =========================================================
# Output / plot configuration
# =========================================================
RESULTS_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "results")

PLOT_CONFIG = {
    "body_x_min": -0.50,
    "body_x_max":  0.50,
    "body_y_min": -0.25,
    "body_y_max":  0.25,
    "link_safety_buffer": 0.03,   # metres – conservative buffer around links
    "boundary_search_step": 0.01, # metres – step along x for boundary search
}

PLANNING_REGIONS = [
    {"name": "B1", "cx": -0.3, "cy":  0.45, "w": 0.3, "h": 0.3, "arm": "L-only"},
    {"name": "B2", "cx":  0.0, "cy":  0.45, "w": 0.3, "h": 0.3, "arm": "Interference"},
    {"name": "B3", "cx":  0.3, "cy":  0.45, "w": 0.3, "h": 0.3, "arm": "R-only"},
    {"name": "B4", "cx": -0.3, "cy": -0.45, "w": 0.3, "h": 0.3, "arm": "L-only"},
    {"name": "B5", "cx":  0.0, "cy": -0.45, "w": 0.3, "h": 0.3, "arm": "Interference"},
    {"name": "B6", "cx":  0.3, "cy": -0.45, "w": 0.3, "h": 0.3, "arm": "R-only"},
]


# =========================================================
# URDF kinematic‑chain parser
# =========================================================
def parse_arm_chain(urdf_path: str, arm_prefix: str):
    """
    Parse the kinematic chain for one arm from the URDF.

    Parameters
    ----------
    urdf_path : str
        Path to the URDF file.
    arm_prefix : str
        ``"left_arm"`` or ``"right_arm"``.

    Returns
    -------
    chain : list[dict]
        Ordered list of joint descriptions from base_link to ee_link.
        Each dict contains:
        ``name``, ``type`` (``"prismatic"``/``"revolute"``/``"fixed"``),
        ``xyz``, ``rpy``, ``axis``, ``lower``, ``upper``, ``child``.
    """
    tree = ET.parse(urdf_path)
    root = tree.getroot()

    # Build lookup: parent_link → [(joint_elem, child_link)]
    parent_map: dict[str, list] = {}
    for joint in root.findall("joint"):
        parent_link = joint.find("parent").get("link")
        child_link = joint.find("child").get("link")
        parent_map.setdefault(parent_link, []).append((joint, child_link))

    chain = []
    # Start from the arm's base link (naming convention: "{arm_prefix}_base_link")
    current_link = f"{arm_prefix}_base_link"
    if current_link not in {l.get("name") for l in root.findall("link")}:
        raise ValueError(
            f"Base link '{current_link}' not found in URDF. "
            f"Available links: {[l.get('name') for l in root.findall('link')]}"
        )
    while True:
        children = parent_map.get(current_link, [])
        # Filter to same arm
        arm_children = [
            (j, c) for j, c in children if c.startswith(arm_prefix)
        ]
        if not arm_children:
            break
        joint_elem, child_link = arm_children[0]
        origin = joint_elem.find("origin")
        if origin is not None:
            xyz = [float(v) for v in origin.get("xyz", "0 0 0").split()]
            rpy = [float(v) for v in origin.get("rpy", "0 0 0").split()]
        else:
            xyz = [0.0, 0.0, 0.0]
            rpy = [0.0, 0.0, 0.0]

        axis_elem = joint_elem.find("axis")
        axis = (
            [float(v) for v in axis_elem.get("xyz", "0 0 0").split()]
            if axis_elem is not None
            else [0.0, 0.0, 0.0]
        )
        limit = joint_elem.find("limit")
        lower = float(limit.get("lower", "0")) if limit is not None else 0.0
        upper = float(limit.get("upper", "0")) if limit is not None else 0.0

        chain.append({
            "name": joint_elem.get("name"),
            "type": joint_elem.get("type"),
            "xyz": np.asarray(xyz, dtype=float),
            "rpy": np.asarray(rpy, dtype=float),
            "axis": np.asarray(axis, dtype=float),
            "lower": lower,
            "upper": upper,
            "child": child_link,
        })
        current_link = child_link
    return chain


def _joint_transform(joint_desc: dict, q_val: float) -> np.ndarray:
    """
    Compute the 4×4 homogeneous transform for a single joint at joint
    value ``q_val``.

    For a **prismatic** joint the translation is the static origin xyz plus
    ``q_val`` along the joint axis.  For a **revolute** joint the rotation
    is the static origin rotation composed with ``q_val`` about the joint
    axis.  A **fixed** joint simply returns the static origin.
    """
    T_origin = xyzrpy_to_T(joint_desc["xyz"], joint_desc["rpy"])
    jtype = joint_desc["type"]
    if jtype == "fixed":
        return T_origin

    if jtype == "prismatic":
        T_motion = np.eye(4)
        T_motion[:3, 3] = joint_desc["axis"] * q_val
        return T_origin @ T_motion

    if jtype == "revolute":
        ax = joint_desc["axis"]
        # Rodrigues formula for rotation about an arbitrary unit axis.
        # The current URDF uses axes of the form (0,0,±1), but this
        # implementation handles general unit axes correctly.
        angle = q_val
        ax_norm = np.linalg.norm(ax)
        if ax_norm < 1e-12:
            return T_origin
        ax = ax / ax_norm
        K = np.array([
            [0, -ax[2], ax[1]],
            [ax[2], 0, -ax[0]],
            [-ax[1], ax[0], 0],
        ])
        R_motion = np.eye(3) + np.sin(angle) * K + (1 - np.cos(angle)) * (K @ K)
        T_motion = np.eye(4)
        T_motion[:3, :3] = R_motion
        return T_origin @ T_motion

    # Fallback
    return T_origin


# =========================================================
# Forward kinematics – all link origins
# =========================================================
def compute_fk_all_links(
    chain: list,
    q: np.ndarray,
    T_vehicle_from_arm: np.ndarray,
) -> dict:
    """
    Compute the vehicle‑frame positions of every link origin given joint
    values ``q``.

    Parameters
    ----------
    chain : list[dict]
        Kinematic chain as returned by :func:`parse_arm_chain`.
    q : ndarray, shape (n_actuated,)
        Joint values for the actuated (non‑fixed) joints, in chain order.
    T_vehicle_from_arm : ndarray, shape (4,4)
        Transform from arm base_link frame to vehicle frame.

    Returns
    -------
    link_positions : dict[str, ndarray]
        ``{child_link_name: vehicle_xyz}`` for every link in the chain,
        including ``base_link`` (at the arm origin).
    """
    T_accum = T_vehicle_from_arm.copy()
    positions = {}

    # Record arm base position
    positions["base_link"] = T_accum[:3, 3].copy()

    q_idx = 0
    for jd in chain:
        if jd["type"] == "fixed":
            T_joint = _joint_transform(jd, 0.0)
        else:
            T_joint = _joint_transform(jd, float(q[q_idx]))
            q_idx += 1
        T_accum = T_accum @ T_joint
        positions[jd["child"]] = T_accum[:3, 3].copy()

    return positions


# =========================================================
# Classify a vehicle‑frame target point into B1‑B6 regions
# =========================================================
def classify_point_region(x: float, y: float) -> str | None:
    """Return 'B1'..'B6' if the point falls inside one of the planning
    regions, otherwise ``None``."""
    for r in PLANNING_REGIONS:
        x_lo = r["cx"] - r["w"] / 2
        x_hi = r["cx"] + r["w"] / 2
        y_lo = r["cy"] - r["h"] / 2
        y_hi = r["cy"] + r["h"] / 2
        if x_lo <= x <= x_hi and y_lo <= y <= y_hi:
            return r["name"]
    return None


# =========================================================
# Compute swept volumes from the ROI table
# =========================================================
def compute_swept_volumes(roi_payload: dict, T_left, T_right, urdf_path: str):
    """
    For every reachable grid point in the ROI table, compute all link
    positions using the *best* IK solution, then group by arm and by
    region.

    Returns
    -------
    swept : dict
        ``swept["left"]``  → dict  region_name → ndarray (N, 3)
        ``swept["right"]`` → dict  region_name → ndarray (N, 3)
    ee_points : dict
        ``ee_points["left"]``  → dict  region_name → ndarray (M, 3)
        ``ee_points["right"]`` → dict  region_name → ndarray (M, 3)
    """
    # Both arms share identical kinematic structure (same joint types,
    # DH parameters, and link lengths) – only the base transform differs.
    # The ROI builder (build_roi_table.py) already exploits this symmetry
    # by using a single left_arm IK chain for both arms, transforming
    # targets into each arm's local frame.  We reuse the same chain here
    # for FK; the arm‑specific base transform (T_left / T_right) converts
    # the result back to the vehicle frame.
    chain = parse_arm_chain(urdf_path, "left_arm")

    roi = roi_payload["data"]

    swept = {"left": {}, "right": {}}
    ee_points = {"left": {}, "right": {}}

    for key, item in roi.items():
        x_v, y_v, z_v = item["vehicle_xyz"]
        region = classify_point_region(x_v, y_v)

        for arm in ("left", "right"):
            entry = item[arm]
            q_best = entry.get("best_solution")
            if q_best is None:
                continue
            q_best = np.asarray(q_best, dtype=float)
            T_base = T_left if arm == "left" else T_right
            link_pos = compute_fk_all_links(chain, q_best, T_base)

            region_key = region if region is not None else "outside"
            swept[arm].setdefault(region_key, [])
            ee_points[arm].setdefault(region_key, [])

            for link_name, pos in link_pos.items():
                swept[arm][region_key].append(pos)

            # Record end‑effector position separately
            ee_pos = np.array([x_v, y_v, z_v], dtype=float)
            ee_points[arm][region_key].append(ee_pos)

    # Convert lists to arrays
    for arm in ("left", "right"):
        for reg in list(swept[arm].keys()):
            swept[arm][reg] = np.asarray(swept[arm][reg], dtype=float)
        for reg in list(ee_points[arm].keys()):
            ee_points[arm][reg] = np.asarray(ee_points[arm][reg], dtype=float)

    return swept, ee_points


# =========================================================
# Overlap detection helpers (XY projection)
# =========================================================
def points_to_xy(pts: np.ndarray) -> np.ndarray:
    """Project (N,3) or (N,2) points to (N,2) XY."""
    return pts[:, :2]


def convex_hull_polygon(pts_2d: np.ndarray):
    """Return the ordered vertices of the convex hull of 2‑D points."""
    if len(pts_2d) < 3:
        return pts_2d
    try:
        hull = ConvexHull(pts_2d)
        return pts_2d[hull.vertices]
    except Exception:
        return pts_2d


def polygons_overlap(poly_a: np.ndarray, poly_b: np.ndarray) -> bool:
    """
    Check if two convex polygons (given as ordered vertex arrays)
    overlap using the Separating Axis Theorem (SAT).
    """
    def _edges(poly):
        edges = []
        n = len(poly)
        for i in range(n):
            edges.append(poly[(i + 1) % n] - poly[i])
        return edges

    def _project(poly, axis):
        dots = poly @ axis
        return dots.min(), dots.max()

    if len(poly_a) < 2 or len(poly_b) < 2:
        return False

    for poly in (poly_a, poly_b):
        for edge in _edges(poly):
            normal = np.array([-edge[1], edge[0]])
            norm = np.linalg.norm(normal)
            if norm < 1e-12:
                continue
            normal /= norm
            min_a, max_a = _project(poly_a, normal)
            min_b, max_b = _project(poly_b, normal)
            if max_a < min_b or max_b < min_a:
                return False
    return True


def compute_overlap_points(pts_a_2d: np.ndarray, pts_b_2d: np.ndarray,
                           grid_step: float = 0.005) -> np.ndarray:
    """
    Return an (M, 2) array of grid points that are inside **both** convex
    hulls (approximation of intersection area for visualization).
    """
    if len(pts_a_2d) < 3 or len(pts_b_2d) < 3:
        return np.empty((0, 2))

    try:
        hull_a = ConvexHull(pts_a_2d)
        hull_b = ConvexHull(pts_b_2d)
    except Exception:
        return np.empty((0, 2))

    # Bounding box of intersection
    verts_a = pts_a_2d[hull_a.vertices]
    verts_b = pts_b_2d[hull_b.vertices]
    x_lo = max(verts_a[:, 0].min(), verts_b[:, 0].min())
    x_hi = min(verts_a[:, 0].max(), verts_b[:, 0].max())
    y_lo = max(verts_a[:, 1].min(), verts_b[:, 1].min())
    y_hi = min(verts_a[:, 1].max(), verts_b[:, 1].max())

    if x_lo >= x_hi or y_lo >= y_hi:
        return np.empty((0, 2))

    xs = np.arange(x_lo, x_hi + grid_step * 0.5, grid_step)
    ys = np.arange(y_lo, y_hi + grid_step * 0.5, grid_step)
    grid = np.array(np.meshgrid(xs, ys)).T.reshape(-1, 2)

    def _in_hull(pts, hull):
        try:
            d = Delaunay(pts[hull.vertices])
            return d.find_simplex(grid) >= 0
        except Exception:
            return np.zeros(len(grid), dtype=bool)

    mask = _in_hull(pts_a_2d, hull_a) & _in_hull(pts_b_2d, hull_b)
    return grid[mask]


# =========================================================
# Safety boundary search
# =========================================================
def _search_one_scenario(
    fixed_arm: str,
    fixed_exclusive: str,
    moving_arm: str,
    interf_region: str,
    ix_lo: float,
    ix_hi: float,
    roi_data: dict,
    T_left,
    T_right,
    chain: list,
    buffer: float,
    step: float,
):
    """
    Core boundary search for one scenario direction.

    *fixed_arm* works exclusively in *fixed_exclusive*.
    *moving_arm* works in *interf_region*, restricted by a boundary.

    For the *left* fixed arm (Scenario A), the moving arm is the right arm
    and we restrict ``x ≥ boundary``, scanning from right→left.
    For the *right* fixed arm (Scenario B), the moving arm is the left arm
    and we restrict ``x ≤ boundary``, scanning from left→right.

    Returns ``(boundary_x, info_dict)``.
    """
    is_scenario_A = (fixed_arm == "left")  # left exclusive, right moving

    def _gather_link_points(arm, ee_targets):
        pts = []
        T_base = T_left if arm == "left" else T_right
        for key, item in roi_data.items():
            entry = item[arm]
            q_best = entry.get("best_solution")
            if q_best is None:
                continue
            x_v, y_v, _ = item["vehicle_xyz"]
            if (x_v, y_v) not in ee_targets:
                continue
            q_best = np.asarray(q_best, dtype=float)
            link_pos = compute_fk_all_links(chain, q_best, T_base)
            for _, pos in link_pos.items():
                pts.append(pos[:2])
        return np.asarray(pts, dtype=float) if pts else np.empty((0, 2))

    def _ee_targets(arm, regions, x_bound=None, bound_side=None):
        targets = set()
        for key, item in roi_data.items():
            if item[arm].get("best_solution") is None:
                continue
            x_v, y_v, _ = item["vehicle_xyz"]
            reg = classify_point_region(x_v, y_v)
            if reg not in regions:
                continue
            if x_bound is not None:
                if bound_side == "left" and x_v > x_bound + 1e-9:
                    continue
                if bound_side == "right" and x_v < x_bound - 1e-9:
                    continue
            targets.add((x_v, y_v))
        return targets

    def _check(fixed_pts, moving_pts, buf):
        if len(fixed_pts) < 3 or len(moving_pts) < 3:
            return False
        ha = convex_hull_polygon(fixed_pts)
        hb = convex_hull_polygon(moving_pts)
        if len(ha) < 3 or len(hb) < 3:
            return False
        if buf > 0:
            ha = _inflate_polygon(ha, buf)
            hb = _inflate_polygon(hb, buf)
        return polygons_overlap(ha, hb)

    # Fixed arm body (independent of boundary)
    fixed_targets = _ee_targets(fixed_arm, {fixed_exclusive})
    fixed_link_pts = _gather_link_points(fixed_arm, fixed_targets)

    x_candidates = np.arange(ix_lo, ix_hi + step * 0.5, step)
    if is_scenario_A:
        x_iter = reversed(x_candidates)
        bound_side = "right"
    else:
        x_iter = iter(x_candidates)
        bound_side = "left"

    best_bx = None
    best_info = None

    for bx in x_iter:
        moving_targets = _ee_targets(
            moving_arm, {interf_region}, x_bound=bx, bound_side=bound_side,
        )
        if not moving_targets:
            best_bx = bx
            constraint = f"x≥{bx:.2f}" if is_scenario_A else f"x≤{bx:.2f}"
            best_info = {
                "boundary_x": bx,
                "fixed_link_pts": fixed_link_pts,
                "moving_link_pts": np.empty((0, 2)),
                "overlap": False,
                "constraint": constraint,
            }
            continue

        moving_link_pts = _gather_link_points(moving_arm, moving_targets)
        overlap = _check(fixed_link_pts, moving_link_pts, buffer)

        if not overlap:
            constraint = f"x≥{bx:.2f}" if is_scenario_A else f"x≤{bx:.2f}"
            best_bx = bx
            best_info = {
                "boundary_x": bx,
                "fixed_link_pts": fixed_link_pts,
                "moving_link_pts": moving_link_pts,
                "overlap": False,
                "constraint": constraint,
            }
        else:
            break

    if best_info is None:
        best_info = {
            "boundary_x": None,
            "fixed_link_pts": fixed_link_pts,
            "moving_link_pts": np.empty((0, 2)),
            "overlap": True,
            "constraint": "none",
        }

    return best_bx, best_info


def find_safety_boundary(
    swept: dict,
    ee_points: dict,
    T_left,
    T_right,
    chain: list,
    roi_payload: dict,
    side: str,
    buffer: float = 0.03,
    step: float = 0.01,
):
    """
    For a given *side* (``"upper"`` = B1/B2/B3 fruit band or ``"lower"``
    = B4/B5/B6), find the x‑boundary inside the interference zone (B2 or
    B5) for two scenarios, each at two buffer levels (0 cm and the
    specified buffer):

    **Scenario A** ("left in exclusive, right in interference"):
      Left arm EE works exclusively in B1 (or B4).  Right arm EE works
      in the interference zone (B2 or B5) restricted to ``x ≥ boundary``.

    **Scenario B** ("right in exclusive, left in interference"):
      Right arm EE works exclusively in B3 (or B6).  Left arm EE works
      in the interference zone restricted to ``x ≤ boundary``.

    Returns
    -------
    results : dict  with keys ``"scenario_A"`` and ``"scenario_B"``.
        Each value is a dict with ``"buffered"`` and ``"raw"`` sub‑dicts,
        each containing ``(boundary_x, info_dict)``.
    """
    if side == "upper":
        interf_region = "B2"
        left_exclusive = "B1"
        right_exclusive = "B3"
    else:
        interf_region = "B5"
        left_exclusive = "B4"
        right_exclusive = "B6"

    for r in PLANNING_REGIONS:
        if r["name"] == interf_region:
            ix_lo = r["cx"] - r["w"] / 2
            ix_hi = r["cx"] + r["w"] / 2
            break

    roi_data = roi_payload["data"]
    common = dict(
        roi_data=roi_data, T_left=T_left, T_right=T_right,
        chain=chain, ix_lo=ix_lo, ix_hi=ix_hi, step=step,
    )

    # ---- Scenario A (left exclusive, right in interf) ----
    bnd_A_buf, info_A_buf = _search_one_scenario(
        fixed_arm="left", fixed_exclusive=left_exclusive,
        moving_arm="right", interf_region=interf_region,
        buffer=buffer, **common,
    )
    bnd_A_raw, info_A_raw = _search_one_scenario(
        fixed_arm="left", fixed_exclusive=left_exclusive,
        moving_arm="right", interf_region=interf_region,
        buffer=0.0, **common,
    )

    info_A_buf["description"] = (
        f"L‑EE in {left_exclusive}; R‑EE in "
        f"{interf_region} ({info_A_buf['constraint']}), "
        f"buf={buffer*100:.0f}cm"
    )
    info_A_raw["description"] = (
        f"L‑EE in {left_exclusive}; R‑EE in "
        f"{interf_region} ({info_A_raw['constraint']}), "
        f"buf=0cm"
    )

    # ---- Scenario B (right exclusive, left in interf) ----
    bnd_B_buf, info_B_buf = _search_one_scenario(
        fixed_arm="right", fixed_exclusive=right_exclusive,
        moving_arm="left", interf_region=interf_region,
        buffer=buffer, **common,
    )
    bnd_B_raw, info_B_raw = _search_one_scenario(
        fixed_arm="right", fixed_exclusive=right_exclusive,
        moving_arm="left", interf_region=interf_region,
        buffer=0.0, **common,
    )

    info_B_buf["description"] = (
        f"R‑EE in {right_exclusive}; L‑EE in "
        f"{interf_region} ({info_B_buf['constraint']}), "
        f"buf={buffer*100:.0f}cm"
    )
    info_B_raw["description"] = (
        f"R‑EE in {right_exclusive}; L‑EE in "
        f"{interf_region} ({info_B_raw['constraint']}), "
        f"buf=0cm"
    )

    return {
        "scenario_A": {
            "buffered": (bnd_A_buf, info_A_buf),
            "raw": (bnd_A_raw, info_A_raw),
        },
        "scenario_B": {
            "buffered": (bnd_B_buf, info_B_buf),
            "raw": (bnd_B_raw, info_B_raw),
        },
    }


def _inflate_polygon(verts: np.ndarray, d: float) -> np.ndarray:
    """Inflate a convex polygon outward by distance ``d``.

    Uses a simple radial expansion from the centroid.  This is an
    approximation that works well for roughly convex, compact shapes but
    does **not** produce a uniformly offset polygon (Minkowski sum with a
    disk).  For the safety‑boundary analysis the approximation is
    conservative enough because the convex hulls are already a superset
    of the true link volumes.
    """
    center = verts.mean(axis=0)
    directions = verts - center
    norms = np.linalg.norm(directions, axis=1, keepdims=True)
    norms = np.maximum(norms, 1e-12)
    return verts + d * directions / norms


# =========================================================
# Drawing helpers (shared with plot_roi_coverage.py style)
# =========================================================
def _draw_vehicle(ax):
    cfg = PLOT_CONFIG
    rect = patches.Rectangle(
        (cfg["body_x_min"], cfg["body_y_min"]),
        cfg["body_x_max"] - cfg["body_x_min"],
        cfg["body_y_max"] - cfg["body_y_min"],
        linewidth=2, edgecolor="gray", facecolor="lightgray",
        alpha=0.25, linestyle="--", label="Vehicle body",
    )
    ax.add_patch(rect)


def _draw_planning_regions(ax, alpha_edge=0.6):
    for r in PLANNING_REGIONS:
        border = patches.Rectangle(
            (r["cx"] - r["w"] / 2, r["cy"] - r["h"] / 2),
            r["w"], r["h"],
            linewidth=1.2, edgecolor="black", facecolor="none",
            alpha=alpha_edge, linestyle="--", zorder=3,
        )
        ax.add_patch(border)
        ax.text(
            r["cx"], r["cy"],
            f'{r["name"]}\n({r["arm"]})',
            ha="center", va="center",
            fontsize=6, color="black", fontweight="bold", zorder=4,
        )


def _setup_ax(ax, title, T_left, T_right):
    _draw_vehicle(ax)
    _draw_planning_regions(ax)
    ax.set_title(title, fontsize=10)
    ax.set_xlabel("x (m)")
    ax.set_ylabel("y (m)")
    ax.set_aspect("equal")
    ax.grid(True, alpha=0.3)
    ax.scatter(T_left[0, 3], T_left[1, 3], c="#819CC4", marker="*", s=180,
               label="Left arm base", zorder=5)
    ax.scatter(T_right[0, 3], T_right[1, 3], c="#8CC19A", marker="*", s=180,
               label="Right arm base", zorder=5)


def _draw_hull(ax, pts_2d, color, label, alpha=0.25, linestyle="-"):
    """Draw a filled convex hull for a set of 2‑D points."""
    if len(pts_2d) < 3:
        return
    try:
        hull = ConvexHull(pts_2d)
    except Exception:
        return
    verts = pts_2d[hull.vertices]
    poly = plt.Polygon(verts, closed=True, facecolor=color,
                       edgecolor=color, alpha=alpha, linewidth=1.5,
                       linestyle=linestyle, label=label, zorder=2)
    ax.add_patch(poly)


# =========================================================
# Main plotting function
# =========================================================
def plot_swept_volume_analysis(
    swept: dict,
    ee_points: dict,
    T_left,
    T_right,
    results_upper: dict,
    results_lower: dict,
):
    """Generate the comprehensive multi‑panel swept‑volume figure."""

    target_z = CONFIG["z_min"]
    buf_cm = PLOT_CONFIG["link_safety_buffer"] * 100

    # ------------------------------------------------------------------
    # Aggregate XY link positions per arm (across all regions)
    # ------------------------------------------------------------------
    def _all_xy(arm):
        pts = []
        for reg, arr in swept[arm].items():
            if len(arr) > 0:
                pts.append(arr[:, :2])
        return np.vstack(pts) if pts else np.empty((0, 2))

    left_all_xy = _all_xy("left")
    right_all_xy = _all_xy("right")

    # Aggregate EE‑only XY per arm
    def _ee_xy(arm):
        pts = []
        for reg, arr in ee_points[arm].items():
            if len(arr) > 0:
                pts.append(arr[:, :2])
        return np.vstack(pts) if pts else np.empty((0, 2))

    left_ee_xy = _ee_xy("left")
    right_ee_xy = _ee_xy("right")

    # ------------------------------------------------------------------
    fig = plt.figure(figsize=(32, 28))
    fig.suptitle(
        f"Dual‑Arm Swept‑Volume Analysis @ z = {target_z:.3f} m",
        fontsize=14, fontweight="bold",
    )

    # ============ Row 1: Overview ============
    # Panel 1: Left arm swept volume
    ax1 = fig.add_subplot(4, 3, 1)
    _setup_ax(ax1, "Left Arm: Link Swept Vol. vs EE Workspace", T_left, T_right)
    if len(left_all_xy) > 0:
        ax1.scatter(left_all_xy[:, 0], left_all_xy[:, 1], s=2, c="#AFC4E4",
                    alpha=0.3, zorder=1)
        _draw_hull(ax1, left_all_xy, "#6A8EC4", "L link swept vol.", alpha=0.15)
    if len(left_ee_xy) > 0:
        _draw_hull(ax1, left_ee_xy, "#2A5CAA", "L EE workspace", alpha=0.20,
                   linestyle="--")
    ax1.legend(loc="upper left", fontsize=7)

    # Panel 2: Right arm swept volume
    ax2 = fig.add_subplot(4, 3, 2)
    _setup_ax(ax2, "Right Arm: Link Swept Vol. vs EE Workspace", T_left, T_right)
    if len(right_all_xy) > 0:
        ax2.scatter(right_all_xy[:, 0], right_all_xy[:, 1], s=2, c="#BEE4C8",
                    alpha=0.3, zorder=1)
        _draw_hull(ax2, right_all_xy, "#5CA86C", "R link swept vol.", alpha=0.15)
    if len(right_ee_xy) > 0:
        _draw_hull(ax2, right_ee_xy, "#2D7A3E", "R EE workspace", alpha=0.20,
                   linestyle="--")
    ax2.legend(loc="upper left", fontsize=7)

    # Panel 3: Combined overlap
    ax3 = fig.add_subplot(4, 3, 3)
    _setup_ax(ax3, "Combined: Dual‑Arm Link Swept Volumes", T_left, T_right)
    _draw_hull(ax3, left_all_xy, "#6A8EC4", "L link swept vol.", alpha=0.20)
    _draw_hull(ax3, right_all_xy, "#5CA86C", "R link swept vol.", alpha=0.20)
    if len(left_all_xy) >= 3 and len(right_all_xy) >= 3:
        overlap_pts = compute_overlap_points(left_all_xy, right_all_xy, grid_step=0.005)
        if len(overlap_pts) > 0:
            ax3.scatter(overlap_pts[:, 0], overlap_pts[:, 1], s=3, c="red",
                        alpha=0.5, label="Body overlap", zorder=3)
    ax3.legend(loc="upper left", fontsize=7)

    # ============ Row 2: Upper band boundaries (raw = 0cm buffer) ============
    bnd_A_raw, info_A_raw = results_upper["scenario_A"]["raw"]
    bnd_B_raw, info_B_raw = results_upper["scenario_B"]["raw"]

    ax4 = fig.add_subplot(4, 3, 4)
    _setup_ax(ax4, "Upper ScA (0cm buf): L in B1, R in B2(x≥bnd)", T_left, T_right)
    _draw_boundary_panel(ax4, info_A_raw, bnd_A_raw)

    ax5 = fig.add_subplot(4, 3, 5)
    _setup_ax(ax5, "Upper ScB (0cm buf): R in B3, L in B2(x≤bnd)", T_left, T_right)
    _draw_boundary_panel(ax5, info_B_raw, bnd_B_raw)

    # Upper buffered Scenario A
    bnd_A_buf, info_A_buf = results_upper["scenario_A"]["buffered"]
    ax6 = fig.add_subplot(4, 3, 6)
    _setup_ax(ax6, f"Upper ScA ({buf_cm:.0f}cm buf): L in B1, R in B2(x≥bnd)",
              T_left, T_right)
    _draw_boundary_panel(ax6, info_A_buf, bnd_A_buf)

    # ============ Row 3: Lower band boundaries ============
    bnd_A_raw_lo, info_A_raw_lo = results_lower["scenario_A"]["raw"]
    bnd_B_raw_lo, info_B_raw_lo = results_lower["scenario_B"]["raw"]

    ax7 = fig.add_subplot(4, 3, 7)
    _setup_ax(ax7, "Lower ScA (0cm buf): L in B4, R in B5(x≥bnd)", T_left, T_right)
    _draw_boundary_panel(ax7, info_A_raw_lo, bnd_A_raw_lo)

    ax8 = fig.add_subplot(4, 3, 8)
    _setup_ax(ax8, "Lower ScB (0cm buf): R in B6, L in B5(x≤bnd)", T_left, T_right)
    _draw_boundary_panel(ax8, info_B_raw_lo, bnd_B_raw_lo)

    # Lower buffered
    bnd_A_buf_lo, info_A_buf_lo = results_lower["scenario_A"]["buffered"]
    ax9 = fig.add_subplot(4, 3, 9)
    _setup_ax(ax9, f"Lower ScA ({buf_cm:.0f}cm buf): L in B4, R in B5(x≥bnd)",
              T_left, T_right)
    _draw_boundary_panel(ax9, info_A_buf_lo, bnd_A_buf_lo)

    # ============ Row 4: Remaining buffered panels + Summary ============
    bnd_B_buf, info_B_buf = results_upper["scenario_B"]["buffered"]
    ax10 = fig.add_subplot(4, 3, 10)
    _setup_ax(ax10, f"Upper ScB ({buf_cm:.0f}cm buf): R in B3, L in B2(x≤bnd)",
              T_left, T_right)
    _draw_boundary_panel(ax10, info_B_buf, bnd_B_buf)

    bnd_B_buf_lo, info_B_buf_lo = results_lower["scenario_B"]["buffered"]
    ax11 = fig.add_subplot(4, 3, 11)
    _setup_ax(ax11, f"Lower ScB ({buf_cm:.0f}cm buf): R in B6, L in B5(x≤bnd)",
              T_left, T_right)
    _draw_boundary_panel(ax11, info_B_buf_lo, bnd_B_buf_lo)

    # Summary panel
    ax12 = fig.add_subplot(4, 3, 12)
    ax12.axis("off")

    def _fmt(bnd, info):
        if bnd is not None:
            return f"  x = {bnd:+.3f} m  ✓"
        return "  No boundary  ✗"

    lines = [
        "══════════════════════════════════════",
        "   Safety Boundary Summary",
        "══════════════════════════════════════",
        f" z={target_z:.3f}m  step={PLOT_CONFIG['boundary_search_step']}m",
        "",
        "─── Upper (B1/B2/B3) ───",
        f" ScA raw:    {_fmt(bnd_A_raw, info_A_raw)}",
        f" ScA buf:    {_fmt(bnd_A_buf, info_A_buf)}",
        f" ScB raw:    {_fmt(bnd_B_raw, info_B_raw)}",
        f" ScB buf:    {_fmt(bnd_B_buf, info_B_buf)}",
        "",
        "─── Lower (B4/B5/B6) ───",
        f" ScA raw:    {_fmt(bnd_A_raw_lo, info_A_raw_lo)}",
        f" ScA buf:    {_fmt(bnd_A_buf_lo, info_A_buf_lo)}",
        f" ScB raw:    {_fmt(bnd_B_raw_lo, info_B_raw_lo)}",
        f" ScB buf:    {_fmt(bnd_B_buf_lo, info_B_buf_lo)}",
        "",
        "══════════════════════════════════════",
        " ScA: L‑EE in exclusive, R in interf",
        " ScB: R‑EE in exclusive, L in interf",
        f" buf = {buf_cm:.0f} cm safety margin",
        " raw = 0 cm (link origins only)",
        "══════════════════════════════════════",
    ]
    ax12.text(0.02, 0.98, "\n".join(lines),
              transform=ax12.transAxes, fontsize=8.5,
              verticalalignment="top", fontfamily="monospace",
              bbox=dict(boxstyle="round", facecolor="wheat", alpha=0.5))

    plt.tight_layout()
    out_path = os.path.join(RESULTS_DIR, "swept_volume_analysis.png")
    os.makedirs(RESULTS_DIR, exist_ok=True)
    plt.savefig(out_path, dpi=200, bbox_inches="tight")
    print(f"Saved swept‑volume analysis to {out_path}")
    plt.close(fig)


def _draw_boundary_panel(ax, info, boundary_x):
    """Draw a single boundary‑search panel."""
    # Support both old (left/right) and new (fixed/moving) key names
    left_pts = info.get("left_link_pts", info.get("fixed_link_pts", np.empty((0, 2))))
    right_pts = info.get("right_link_pts", info.get("moving_link_pts", np.empty((0, 2))))

    if len(left_pts) >= 3:
        _draw_hull(ax, left_pts, "#6A8EC4", "Fixed arm body", alpha=0.25)
        ax.scatter(left_pts[:, 0], left_pts[:, 1], s=1, c="#AFC4E4", alpha=0.2)

    if len(right_pts) >= 3:
        _draw_hull(ax, right_pts, "#5CA86C", "Moving arm body", alpha=0.25)
        ax.scatter(right_pts[:, 0], right_pts[:, 1], s=1, c="#BEE4C8", alpha=0.2)

    if boundary_x is not None:
        ax.axvline(boundary_x, color="red", linewidth=2, linestyle="-",
                   label=f"Boundary x={boundary_x:.3f}", zorder=6)
        # Force y limits before shading
        ax.set_ylim(-0.85, 0.85)
        y_lo, y_hi = ax.get_ylim()
        ax.fill_betweenx([y_lo, y_hi], PLOT_CONFIG["body_x_min"] - 0.5, boundary_x,
                         color="#AFC4E4", alpha=0.05, zorder=0)
        ax.fill_betweenx([y_lo, y_hi], boundary_x, PLOT_CONFIG["body_x_max"] + 0.5,
                         color="#BEE4C8", alpha=0.05, zorder=0)

    overlap_flag = info.get("overlap", True)
    status = "✗ OVERLAP" if overlap_flag else "✓ SAFE"
    ax.set_title(ax.get_title() + f"  [{status}]", fontsize=9)
    ax.legend(loc="upper left", fontsize=6)


# =========================================================
# Per‑region swept volume detail plot
# =========================================================
def plot_per_region_swept_volumes(swept, ee_points, T_left, T_right):
    """
    Produce a figure with one subplot per planning region, showing both
    arms' link swept volumes within that region.
    """
    regions_to_plot = ["B1", "B2", "B3", "B4", "B5", "B6"]
    fig, axes = plt.subplots(2, 3, figsize=(21, 14))
    fig.suptitle("Per‑Region Link Swept Volumes (XY projection)", fontsize=13)

    for idx, reg_name in enumerate(regions_to_plot):
        ax = axes[idx // 3][idx % 3]
        _setup_ax(ax, f"Region {reg_name}", T_left, T_right)

        for arm, color_scatter, color_hull, label in [
            ("left",  "#AFC4E4", "#6A8EC4", "L links"),
            ("right", "#BEE4C8", "#5CA86C", "R links"),
        ]:
            pts = swept[arm].get(reg_name, np.empty((0, 3)))
            if len(pts) > 0:
                xy = pts[:, :2]
                ax.scatter(xy[:, 0], xy[:, 1], s=2, c=color_scatter, alpha=0.4)
                _draw_hull(ax, xy, color_hull, label, alpha=0.15)

            ee = ee_points[arm].get(reg_name, np.empty((0, 3)))
            if len(ee) > 0:
                ax.scatter(ee[:, 0], ee[:, 1], s=6, c=color_hull, marker="x",
                           alpha=0.6, label=f"{arm[0].upper()} EE targets", zorder=4)

        ax.legend(loc="upper left", fontsize=6)

    plt.tight_layout()
    out_path = os.path.join(RESULTS_DIR, "per_region_swept_volumes.png")
    plt.savefig(out_path, dpi=200, bbox_inches="tight")
    print(f"Saved per‑region plot to {out_path}")
    plt.close(fig)


# =========================================================
# Main
# =========================================================
def main():
    urdf_path = CONFIG["urdf_path"]
    roi_file = CONFIG["roi_table_file"]

    if not os.path.exists(roi_file):
        print(f"Error: ROI table not found at {roi_file}. Run build_roi_table.py first.")
        return

    print("Loading ROI table …")
    with open(roi_file, "rb") as f:
        roi_payload = pickle.load(f)

    T_left, T_right = load_base_transforms_from_urdf(
        urdf_path, CONFIG["left_base_joint"], CONFIG["right_base_joint"],
    )
    print(f"Left base:  {T_left[:3, 3]}")
    print(f"Right base: {T_right[:3, 3]}")

    # ------------------------------------------------------------------
    print("Computing swept volumes …")
    swept, ee_points = compute_swept_volumes(roi_payload, T_left, T_right, urdf_path)

    for arm in ("left", "right"):
        total = sum(len(v) for v in swept[arm].values())
        print(f"  {arm} arm: {total} link‑position samples across "
              f"{len(swept[arm])} regions")

    # ------------------------------------------------------------------
    print("Searching safety boundaries …")
    chain = parse_arm_chain(urdf_path, "left_arm")

    results_upper = find_safety_boundary(
        swept, ee_points, T_left, T_right, chain, roi_payload,
        side="upper",
        buffer=PLOT_CONFIG["link_safety_buffer"],
        step=PLOT_CONFIG["boundary_search_step"],
    )
    results_lower = find_safety_boundary(
        swept, ee_points, T_left, T_right, chain, roi_payload,
        side="lower",
        buffer=PLOT_CONFIG["link_safety_buffer"],
        step=PLOT_CONFIG["boundary_search_step"],
    )

    for label, results in [("Upper", results_upper), ("Lower", results_lower)]:
        for sc in ("scenario_A", "scenario_B"):
            for lvl in ("raw", "buffered"):
                bnd, info = results[sc][lvl]
                desc = info.get("description", "")
                tag = f"{label} {sc} ({lvl})"
                if bnd is not None:
                    print(f"  {tag}: x = {bnd:+.3f} m  [{desc}]")
                else:
                    print(f"  {tag}: NO safe boundary  [{desc}]")

    # ------------------------------------------------------------------
    print("Generating plots …")
    plot_swept_volume_analysis(
        swept, ee_points, T_left, T_right,
        results_upper, results_lower,
    )
    plot_per_region_swept_volumes(swept, ee_points, T_left, T_right)

    print("Done.")


if __name__ == "__main__":
    main()
